In [1]:
import numpy as np

In [128]:
class Perceptron():
    def __init__(self, learningRate, nEpochs, train_X, train_y):
        # Generate random seed (currently static for testing)
        np.random.seed(1)
        
        nFeatures = X.shape[1]
        self.weights = np.array([])
        self.nEpochs = nEpochs
        self.learningRate = learningRate
        
        # Generate random weight array (is this necessary or can we start with zero weights?)
        for i in range(nFeatures+1):
            #self.weights = np.append(self.weights,2*np.random.random()-1)
            self.weights = np.append(self.weights,0.0)
            
    def predict(self,X):
        fire = self.weights[0]
        fire += np.dot(X,self.weights[1:])
        return 1.0 if fire >= 0.0 else 0.0
        
    def train(self,X,y):
        for epoch in range(self.nEpochs):
            sumError = 0.0
            for i in range(X.shape[0]):
                prediction = self.predict(X[i])
                error = y[i] - prediction
                sumError += error**2
                self.weights[0] += self.learningRate * error
                for j in range(1,X.shape[1]+1):
                    self.weights[j] = self.weights[j] + self.learningRate * error * X[i,j-1]
            #print("Epoch = %d, learningRate = %.3f, Error = %.3f" % (epoch, self.learningRate, sumError))
        
    

In [129]:
X=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y=np.array([0,0,1,1])
test = Perceptron(0.1,100,X,y)
test.train(X,y)

In [130]:
test.predict(np.array([1,0,0]))

1.0

In [24]:
test.weights[1:]

array([ 0.44064899, -0.99977125])

In [30]:
inputs = np.array([2.7810836,2.550537003])

In [37]:
np.dot(inputs,test.weights[1:])

-1.3244718978117143

In [69]:
test.predict(inputs)

0.0

In [38]:
dataset = np.array([[2.7810836,2.550537003,0],
[1.465489372,2.362125076,0],
[3.396561688,4.400293529,0],
[1.38807019,1.850220317,0],
[3.06407232,3.005305973,0],
[7.627531214,2.759262235,1],
[5.332441248,2.088626775,1],
[6.922596716,1.77106367,1],
[8.675418651,-0.242068655,1],
[7.673756466,3.508563011,1]])

In [45]:
X = dataset[:,:-1]
y = dataset[:,-1]

In [103]:
y

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [79]:
X.shape[1]

2

In [58]:
X[0]

array([2.7810836, 2.550537 ])

In [64]:
test.predict(X[1])

0.0

In [96]:
test.train(X,y)

Epoch = 0, learningRate = 0.100, Error = 1.000
Epoch = 1, learningRate = 0.100, Error = 1.000
Epoch = 2, learningRate = 0.100, Error = 1.000
Epoch = 3, learningRate = 0.100, Error = 0.000
Epoch = 4, learningRate = 0.100, Error = 0.000


In [87]:
X

array([1.46548937, 2.36212508])

In [93]:
print(test.weights)

[-0.26595599  0.65180791 -1.15902235]


3